version: '3.8'

services:
  booklibraryapi:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    #   - ConnectionStrings__BookLibraryContext=Server=postgres;Port=5432;Database=booklibrarydb;User Id=postgres;Password=yourpassword;
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: LibraryCatalogDocker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: